CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT "user",
    req_limit INT NOT NULL DEFAULT 20,
    time_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)