const express = require("express");
const http = require("http");
const https = require("https");
const cors = require("cors");
const swaggerJsDoc = require("swagger-jsdoc");
const swaggerUi = require("swagger-ui-express");

const app = express();
app.use(cors());
app.use(express.json({ limit: "1mb" }));
app.use(express.urlencoded({ limit: "1mb", extended: true }));

// Swagger configuration
const swaggerOptions = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "AI Image Analysis API",
      version: "1.0.0",
      description: "API for analyzing images using BLIP and generating funny captions with Mistral AI",
    },
    servers: [
      {
        url: "http://localhost:3001",
        description: "Development server",
      },
    ],
  },
  apis: ["./minstral.js"], // Path to the API routes file
};

const swaggerDocs = swaggerJsDoc(swaggerOptions);
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerDocs));

const LLM_HOST = "localhost";
const LLM_PORT = 11434;
const ANALYZE_HOST = "127.0.0.1";
const ANALYZE_PORT = 5000;
const EXTERNAL_CAPTION_URL = "http://localhost:11434/completion";

/**
 * @swagger
 * /v1/chat/completions:
 *   post:
 *     summary: Chat with Mistral LLM
 *     description: Send messages to the Mistral language model and get a response
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               messages:
 *                 type: array
 *                 items:
 *                   type: object
 *                   properties:
 *                     role:
 *                       type: string
 *                       example: "user"
 *                     content:
 *                       type: string
 *                       example: "Hello, how are you?"
 *     responses:
 *       200:
 *         description: Successful response
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 content:
 *                   type: string
 *       500:
 *         description: Server error
 */
app.post("/v1/chat/completions", (req, res) => {
  const data = JSON.stringify({
    prompt:
      req.body.messages.map((m) => `${m.role}: ${m.content}`).join("\n") +
      "\nassistant:",
    n_predict: 100,
  });

  const options = {
    hostname: LLM_HOST,
    port: LLM_PORT,
    path: "/completion",
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Content-Length": data.length,
    },
  };

  const request = http.request(options, (response) => {
    let body = "";
    response.on("data", (chunk) => (body += chunk));
    response.on("end", () => {
      try {
        const json = JSON.parse(body);
        res.json({ content: json.content });
        console.log("Response from LLM:", json.content);
      } catch (e) {
        res.status(500).json({ error: e.message, body });
      }
    });
  });
  request.on("error", (err) => res.status(500).json({ error: err.message }));
  request.write(data);
  request.end();
});

/**
 * @swagger
 * /analyze:
 *   post:
 *     summary: Analyze image and generate captions
 *     description: Upload an image to get a description from BLIP AI and an enhanced funny caption from Mistral
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               image:
 *                 type: string
 *                 format: base64
 *                 description: Base64 encoded image (JPEG or PNG)
 *     responses:
 *       200:
 *         description: Successful analysis
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 caption:
 *                   type: string
 *                   description: Original image description from BLIP
 *                   example: "a drawing of a boy with purple eyes"
 *                 description:
 *                   type: string
 *                   description: Alternative description from BLIP
 *                 enhanced_description:
 *                   type: string
 *                   description: Funny caption generated by Mistral AI
 *                   example: "and green hair, holding a pink flamingo as a pet"
 *       413:
 *         description: Image too large
 *       500:
 *         description: Server error
 */
// Accept image analysis requests from the web client and forward to local analyze service
app.post("/analyze", (req, res) => {
  console.log("Received /analyze request");
  const payload = JSON.stringify(req.body || {});

  const options = {
    hostname: ANALYZE_HOST,
    port: ANALYZE_PORT,
    path: "/api/blip/analyze",
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Content-Length": Buffer.byteLength(payload),
      ...(req.headers.authorization
        ? { Authorization: req.headers.authorization }
        : {}),
    },
  };

  const request = http.request(options, (response) => {
    console.log("Received response from BLIP service");
    let body = "";
    response.on("data", (chunk) => (body += chunk));
    response.on("end", () => {
      console.log("BLIP response body:", body);
      try {
        const json = JSON.parse(body);

        // Optionally forward caption to external endpoint if configured
        if (EXTERNAL_CAPTION_URL && json && json.caption) {
          try {
            console.log("Forwarding caption to:", EXTERNAL_CAPTION_URL);
            const { URL } = require("url");
            const target = new URL(EXTERNAL_CAPTION_URL);
            const proto = target.protocol === "https:" ? https : http;
            console.log("Using protocol:", target.protocol);
            const fOptions = {
              hostname: target.hostname,
              port: target.port || (target.protocol === "https:" ? 443 : 80),
              path: target.pathname + (target.search || ""),
              method: "POST",
              headers: {
                "Content-Type": "application/json",
                "ngrok-skip-browser-warning": "true",
              },
            };
            console.log("Request options:", fOptions);
            const fReq = proto.request(fOptions, (fRes) => {
              console.log("Mistral response status:", fRes.statusCode);
              let fBody = "";
              fRes.on("data", (c) => (fBody += c));
              fRes.on("end", () => {
                try {
                  const mistralResponse = JSON.parse(fBody);
                  console.log("Mistral content:", mistralResponse.content);
                  // Add Mistral's enhanced description to the response
                  json.enhanced_description = mistralResponse.content;
                } catch (e) {
                  console.error("Failed to parse Mistral response:", e.message);
                }
                // Send response after Mistral completes
                res.json(json);
              });
            });
            fReq.on("error", (e) => {
              console.error("Caption forward failed:", e.message);
              // Send response even if Mistral fails
              res.json(json);
            });
            const payload = JSON.stringify({
              prompt: `Make a funny caption for this image, one sentence 15 words max: ${json.caption}`,
              n_predict: 100,
            });
            console.log("Sending to Mistral:", payload);
            fReq.write(payload);
            fReq.end();
          } catch (e) {
            console.error("Failed to forward caption:", e.message);
            res.json(json);
          }
        } else {
          console.log("No EXTERNAL_CAPTION_URL set or no caption to forward.");
          res.json(json);
        }
      } catch (e) {
        res.status(500).json({ error: e.message, body });
      }
    });
  });

  request.on("error", (err) => res.status(500).json({ error: err.message }));
  request.write(payload);
  request.end();
});

//make sure THIS PORT is forwarded to the ngrok port
app.listen(3001, () => console.log("Proxy running on port 3001"));
